# Generated by Django 4.2.13 on 2024-07-08 10:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("complaint", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="complaint",
            old_name="cp",
            new_name="postal_code",
        ),
    ]
