# Generated by Django 4.2.13 on 2024-07-08 13:55

import complaint.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to=complaint.models.user_directory_path),
        ),
    ]
