# Generated by Django 4.2.13 on 2024-07-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaint", "0003_complaint_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="location",
            field=models.CharField(blank=True, null=True),
        ),
    ]
