# Generated by Django 4.2.13 on 2024-07-08 22:32

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0004_complaint_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
